//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;

    public partial class CollegeEntities : DbContext
    {
        public CollegeEntities()
            : base("name=CollegeEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Enrollment> Enrollments { get; set; }
        public virtual DbSet<Instructor> Instructors { get; set; }
        public virtual DbSet<Major> Majors { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<Student> Students { get; set; }

        public void deleteEnrollments(Student deleteStudent)
        {
            foreach (var enrollment in this.Enrollments.Where(c => c.Student_Id == deleteStudent.Id))
            {
                this.Enrollments.Remove(enrollment);
            }
        }
        public void deleteEnrollments(Section deleteSection)
        {
            foreach (var enrollment in Enrollments.Where(c => c.Section_Id == deleteSection.Id))
            {
                Enrollments.Remove(enrollment);
            }
        }
        public void deleteSections(Course deleteCourse)
        {
            foreach (var section in Sections.Where(c => c.Course_Id == deleteCourse.Id))
            {
                deleteEnrollments(section);
                Sections.Remove(section);
            }
        }
    }
}
